CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
ORYX_ENABLE = no
RGB_MATRIX_CUSTOM_KB = yes
SPACE_CADET_ENABLE = no
CAPS_WORD_ENABLE = yes

SRC += oneshot.c
SRC += swapper.c

REPEAT_KEY_ENABLE = yes

RAW_ENABLE = yes
VIA_ENABLE = yes
